### PR TITLE
Add 2d viewport hud to c# ragdoll example

### PR DESCRIPTION
**Pull request by JimMarlowe**
This example show the technique of using a 2D viewport as a hud, having the same real estate as the 3D viewport. The non-clearing renderpath makes it all work, and then you just operate both scenes as separate but equal entities. I had a heck of a time making the 2D scene elements, only because I haven't done that before, it could be better, but demos well.  There are new features to make the HUD work. I added the rotating coin to make sure animated sprites work. Using the "U" key, you can change the mass of the ball, "I" = Speed, "O" = Size, then you can see the appropriate HUD change in response to your selection.  Then fire at will, or Jack, as it were. When Jack is hit, he gets the donuts blown out of him. Once all the Jacks are down, you can press "R" to restart the "level".

### CODE REVIEW

**Comment by JimMarlowe** [comment]
And I enhanced the sample code some, to be able to write to the instruction text after it has been created, and ensured the cursor is visible after it exits an example program.

**Comment by JoshEngebretson** [comment]
Thanks for the PR, I plan on checking it out soon 🇺🇸

**Comment by JimMarlowe** [comment]
Retrofitted the cpp ragdoll example with the 2 viewport hud. I also added sparkles to the donuts, because you need that.

**Comment by JoshEngebretson** [comment]
Cool, I landed this in #93

The feature examples are minimal and targeted to the feature they are showcasing.  The plan is also to keep the ones ported from Urho in sync.  So, created a Mods folder and a README to describe the mod and one in the mods folder on hope to apply it.

**Pull request merged**
