### PR TITLE
Project based custom editors

### PR DESCRIPTION
**Pull request by shaddockh**
This PR extends the editor plugin example with an example of how to create a custom editor for a filetype.  This is tied to PR #808 in the main repo.

### CODE REVIEW

**Comment by shaddockh** [comment]
Hey, hold off on merging this.  I'd like to make a more useful example.

**Comment by shaddockh** [comment]
Ok, this is a more interesting example of a custom editor.  Basically a front-end to manipulating a structured JSON file.

**Comment by JoshEngebretson** [comment]
I gave it a whirl on master Atomic Editor!  Very cool to see the confluence of the subsystems and providing a custom editor for json data through the webview is definitely an interesting example! Great work :)

**Comment by mattbenic** [comment]
Cool idea :) :+1:

**Pull request merged**
