### PR TITLE
Update examples to use new Events and Enums

### PR DESCRIPTION
**Pull request by shaddockh**
@JoshEngebretson This updates all the JS and TS examples to use the new enums and event model that just landed on master.  I've gone through and tested them, but it might be a good idea for someone to do a second pass.

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
Holy 🐮 ! 

Do the current examples run with the changes now on master with "backwards compatibility mode"?  Does +249 and -21, 713 lines seem like the right diff here, missing a d.ts or fine to remove now?

**Comment by JoshEngebretson** [comment]
BTW, once this lands we should update the submodule commit for examples on master...

**Comment by shaddockh** [comment]
There is no need for the d.ts files now since the editor will automatically pull the latest d.ts from the bundle.  By leaving those d.ts files in there, they get stale and out of sync with the latest.  If necessary, people can always generate an external project via the menu and create the tsconfig and d.ts files.

The current examples should work with the latest master.  Also, since both roboman and the editor plugin examples have old d.ts files in them, they should also still work but would need to be updated if the latest d.ts file is used.  (which this PR already does).  Regardless, I don't think this PR is urgent if you want some time to look it over.

**Comment by JoshEngebretson** [comment]
Ok, cool, I thought maybe these .d.ts were "special", good to know they aren't :)

I say we go for it on this one, better to run into example issues early and appreciate that you did initial test battery 🚀 Updates look great, nice seasoning, thanks!

I'll update the submodule commit, whoosh!

**Pull request merged**
